use crate::lexer::QuoteLikeMode;
use crate::SyntaxKind;

use super::super::Parser;

impl Parser<'_> {
    pub fn qw_expr(&mut self) {
        self.builder.start_node(SyntaxKind::QW_EXPR.into());

        // "qw"
        self.expect(SyntaxKind::QW_KW);
        // Begin quote-like lexing for qw BEFORE skipping trivia so '#' etc. are treated as delimiters
        self.lexer
            .begin_quote_like(SyntaxKind::QW_KW, QuoteLikeMode::QW);
        self.skip_trivia();
        // Opening delimiter
        if !self.at(SyntaxKind::DELIMITER) {
            self.error("Expected delimiter");
            self.builder.finish_node();
            return;
        }
        self.bump();

        // Parse words inside qw() - lexer provides QW_STRING tokens directly
        while !self.at(SyntaxKind::DELIMITER) && !self.at_end() {
            self.skip_trivia();

            // Expect QW_STRING tokens from the lexer
            if self.at(SyntaxKind::QW_STRING) {
                self.bump(); // Consume QW_STRING token
            } else {
                // If we encounter unexpected token, break
                break;
            }
        }

        // Closing delimiter
        self.expect(SyntaxKind::DELIMITER);

        self.builder.finish_node();

        // Do not force lexer default context; parser drives context.
        self.skip_trivia();
    }

    pub fn q_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::Q_EXPR,
            SyntaxKind::Q_KW,
            SyntaxKind::LITERAL_STRING,
        );
    }

    pub fn qq_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QQ_EXPR,
            SyntaxKind::QQ_KW,
            SyntaxKind::INTERPOLATED_STRING,
        );
    }

    pub fn qx_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QX_EXPR,
            SyntaxKind::QX_KW,
            SyntaxKind::INTERPOLATED_STRING,
        );
    }

    pub fn m_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::M_EXPR,
            SyntaxKind::M_KW,
            SyntaxKind::REGEX_PATTERN,
        );
    }

    pub fn qr_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QR_EXPR,
            SyntaxKind::QR_KW,
            SyntaxKind::REGEX_PATTERN,
        );
    }

    pub fn s_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::S_EXPR,
            SyntaxKind::S_KW,
            SyntaxKind::REGEX_PATTERN,
            SyntaxKind::INTERPOLATED_STRING,
            SyntaxKind::S_FLAGS,
        );
    }

    pub fn tr_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::TR_EXPR,
            SyntaxKind::TR_KW,
            SyntaxKind::TR_SEARCH_LIST,
            SyntaxKind::TR_REPLACEMENT_LIST,
            SyntaxKind::TR_FLAGS,
        );
    }

    pub fn y_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::TR_EXPR,
            SyntaxKind::Y_KW,
            SyntaxKind::TR_SEARCH_LIST,
            SyntaxKind::TR_REPLACEMENT_LIST,
            SyntaxKind::TR_FLAGS,
        );
    }

    fn parse_q_family_expr(
        &mut self,
        expr_kind: SyntaxKind,
        kw_kind: SyntaxKind,
        string_kind: SyntaxKind,
    ) {
        self.builder.start_node(expr_kind.into());

        // "q", "qq", or "qx"
        self.expect(kw_kind);
        // Begin quote-like lexing BEFORE skipping trivia
        let mode = match kw_kind {
            SyntaxKind::Q_KW | SyntaxKind::QQ_KW | SyntaxKind::QX_KW => QuoteLikeMode::Q,
            SyntaxKind::M_KW => QuoteLikeMode::M,
            SyntaxKind::QR_KW => QuoteLikeMode::QR,
            _ => unreachable!("Unexpected keyword: {:?}", kw_kind),
        };
        self.lexer.begin_quote_like(kw_kind, mode);
        self.skip_trivia();

        // Opening delimiter
        if !self.at(SyntaxKind::DELIMITER) {
            self.error("Expected delimiter");
            self.builder.finish_node();
            return;
        }
        self.bump();

        // Parse content inside - handle both pre-tokenized string content and individual tokens
        // Content may be empty
        if self.at(string_kind) {
            self.bump();
        }

        // Closing delimiter (should be DELIMITER token with matching text)
        self.expect(SyntaxKind::DELIMITER);

        // For regex expressions (m and qr), consume optional flags generated by lexer
        if (expr_kind == SyntaxKind::M_EXPR && self.at(SyntaxKind::M_FLAGS))
            || (expr_kind == SyntaxKind::QR_EXPR && self.at(SyntaxKind::QR_FLAGS))
        {
            self.bump();
        }

        self.builder.finish_node();

        // Parser drives context; no lexer default flip.
        self.skip_trivia();
    }

    fn parse_two_part_expr(
        &mut self,
        expr_kind: SyntaxKind,
        kw_kind: SyntaxKind,
        first_part_kind: SyntaxKind,
        second_part_kind: SyntaxKind,
        flags_kind: SyntaxKind,
    ) {
        self.builder.start_node(expr_kind.into());

        // Keyword (e.g., "s", "tr", "y")
        self.expect(kw_kind);
        // Begin quote-like lexing for two-part operators BEFORE skipping trivia
        let mode = match kw_kind {
            SyntaxKind::S_KW => QuoteLikeMode::S,
            SyntaxKind::TR_KW | SyntaxKind::Y_KW => QuoteLikeMode::TR,
            _ => unreachable!("Unexpected keyword: {:?}", kw_kind),
        };
        self.lexer.begin_quote_like(kw_kind, mode);
        self.skip_trivia();

        // Opening delimiter: capture the opening char to decide paired vs symmetric
        let open_ch = match self.current_text() {
            Some(text) if self.at(SyntaxKind::DELIMITER) => {
                let mut chars = text.chars();
                chars.next().unwrap_or('/')
            }
            _ => {
                self.error("Expected delimiter");
                self.builder.finish_node();
                return;
            }
        };
        self.bump();
        self.skip_trivia();

        // First content part (pattern/search list)
        if self.at(first_part_kind) {
            self.bump();
            self.skip_trivia();
        }

        // Middle delimiter (closing first part delimiter)
        self.expect(SyntaxKind::DELIMITER);
        self.skip_trivia();

        // Second part may have its own opening delimiter (for paired delimiters)
        let closing_delim = Self::get_closing_delimiter(open_ch);
        let second_is_paired = matches!(closing_delim, ')' | ']' | '}' | '>');
        if second_is_paired && self.at(SyntaxKind::DELIMITER) {
            self.bump(); // Opening delimiter for second part
            self.skip_trivia();
        }

        // Second content part (replacement/replacement list)
        if self.at(second_part_kind) {
            self.bump();
            self.skip_trivia();
        }

        // Closing delimiter (for second part)
        self.expect(SyntaxKind::DELIMITER);

        // Optional flags - only skip trivia if we have flags to consume
        if self.at(flags_kind) {
            self.skip_trivia();
            self.bump();
        }

        self.builder.finish_node();

        // Parser drives context; no lexer default flip.
        self.skip_trivia();
    }

    /// Get the matching closing delimiter for an opening delimiter
    fn get_closing_delimiter(opening: char) -> char {
        match opening {
            '(' => ')',
            '[' => ']',
            '{' => '}',
            '<' => '>',
            // For symmetric delimiters, the closing is the same as opening
            ch => ch,
        }
    }
}
