use crate::SyntaxKind;

use super::super::Parser;

impl Parser<'_> {
    pub fn qw_expr(&mut self) {
        self.builder.start_node(SyntaxKind::QW_EXPR.into());

        // "qw"
        self.expect(SyntaxKind::QW_KW);
        self.skip_trivia();

        // Consume opening delimiter (should be DELIMITER token)
        let Some(closing_delim) = self.current_delimiter().map(Self::get_closing_delimiter) else {
            self.error("Expected qw delimiter");
            self.builder.finish_node();
            return;
        };

        // Consume opening delimiter
        self.expect(SyntaxKind::DELIMITER);

        // Parse words inside qw() - lexer provides QW_STRING tokens directly
        while !self.at_delimiter(closing_delim) && !self.at_end() {
            self.skip_trivia();

            // Expect QW_STRING tokens from the lexer
            if self.at(SyntaxKind::QW_STRING) {
                self.bump(); // Consume QW_STRING token
            } else {
                // If we encounter unexpected token, break
                break;
            }
        }

        // Closing delimiter (should be DELIMITER token with matching text)
        self.expect_delimiter(closing_delim);

        self.builder.finish_node();

        // Set lexer context to ExpectingOperator after completing the qw expression
        // This allows proper parsing of operators like 'x' that follow qw expressions
        self.set_lexer_context(crate::lexer::LexerContext::ExpectingOperator);

        // Force a fresh token fetch to ensure the context change takes effect
        // Skip any trivia and refresh the current token with the new context
        self.skip_trivia();
    }

    pub fn q_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::Q_EXPR,
            SyntaxKind::Q_KW,
            SyntaxKind::LITERAL_STRING,
        );
    }

    pub fn qq_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QQ_EXPR,
            SyntaxKind::QQ_KW,
            SyntaxKind::INTERPOLATED_STRING,
        );
    }

    pub fn qx_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QX_EXPR,
            SyntaxKind::QX_KW,
            SyntaxKind::INTERPOLATED_STRING,
        );
    }

    pub fn m_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::M_EXPR,
            SyntaxKind::M_KW,
            SyntaxKind::REGEX_PATTERN,
        );
    }

    pub fn qr_expr(&mut self) {
        self.parse_q_family_expr(
            SyntaxKind::QR_EXPR,
            SyntaxKind::QR_KW,
            SyntaxKind::REGEX_PATTERN,
        );
    }

    pub fn s_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::S_EXPR,
            SyntaxKind::S_KW,
            SyntaxKind::REGEX_PATTERN,
            SyntaxKind::INTERPOLATED_STRING,
            SyntaxKind::S_FLAGS,
        );
    }

    pub fn tr_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::TR_EXPR,
            SyntaxKind::TR_KW,
            SyntaxKind::TR_SEARCH_LIST,
            SyntaxKind::TR_REPLACEMENT_LIST,
            SyntaxKind::TR_FLAGS,
        );
    }

    pub fn y_expr(&mut self) {
        self.parse_two_part_expr(
            SyntaxKind::TR_EXPR,
            SyntaxKind::Y_KW,
            SyntaxKind::TR_SEARCH_LIST,
            SyntaxKind::TR_REPLACEMENT_LIST,
            SyntaxKind::TR_FLAGS,
        );
    }

    fn parse_q_family_expr(
        &mut self,
        expr_kind: SyntaxKind,
        kw_kind: SyntaxKind,
        string_kind: SyntaxKind,
    ) {
        self.builder.start_node(expr_kind.into());

        // "q", "qq", or "qx"
        self.expect(kw_kind);
        self.skip_trivia();

        // Consume opening delimiter (should be DELIMITER token)
        // Get the delimiter text to determine the closing delimiter
        let Some(closing_delim) = self.current_delimiter().map(Self::get_closing_delimiter) else {
            self.error("Expected qw delimiter");
            self.builder.finish_node();
            return;
        };

        // Consume opening delimiter
        self.expect(SyntaxKind::DELIMITER);

        // Parse content inside - handle both pre-tokenized string content and individual tokens
        self.expect(string_kind);

        // Closing delimiter (should be DELIMITER token with matching text)
        self.expect_delimiter(closing_delim);

        // For regex expressions (m and qr), consume optional flags generated by lexer
        if (expr_kind == SyntaxKind::M_EXPR && self.at(SyntaxKind::M_FLAGS))
            || (expr_kind == SyntaxKind::QR_EXPR && self.at(SyntaxKind::QR_FLAGS))
        {
            self.bump();
        }

        self.builder.finish_node();

        // Set lexer context to ExpectingOperator after completing the q-family expression
        // This allows proper parsing of operators like 'x' that follow q expressions
        self.set_lexer_context(crate::lexer::LexerContext::ExpectingOperator);

        // Force a fresh token fetch to ensure the context change takes effect
        // Skip any trivia and refresh the current token with the new context
        self.skip_trivia();
    }

    fn parse_two_part_expr(
        &mut self,
        expr_kind: SyntaxKind,
        kw_kind: SyntaxKind,
        first_part_kind: SyntaxKind,
        second_part_kind: SyntaxKind,
        flags_kind: SyntaxKind,
    ) {
        self.builder.start_node(expr_kind.into());

        // Keyword (e.g., "s", "tr", "y")
        self.expect(kw_kind);
        self.skip_trivia();

        // Opening delimiter
        self.expect(SyntaxKind::DELIMITER);
        self.skip_trivia();

        // First content part (pattern/search list)
        if self.at(first_part_kind) {
            self.bump();
            self.skip_trivia();
        }

        // Middle delimiter (closing first part delimiter)
        self.expect(SyntaxKind::DELIMITER);
        self.skip_trivia();

        // For asymmetric delimiters, there might be another opening delimiter for second part
        if self.at(SyntaxKind::DELIMITER) {
            self.bump(); // Opening delimiter for second part
            self.skip_trivia();
        }

        // Second content part (replacement/replacement list)
        if self.at(second_part_kind) {
            self.bump();
            self.skip_trivia();
        }

        // Closing delimiter (for second part)
        self.expect(SyntaxKind::DELIMITER);

        // Optional flags - only skip trivia if we have flags to consume
        if self.at(flags_kind) {
            self.skip_trivia();
            self.bump();
        }

        self.builder.finish_node();

        // Set lexer context to ExpectingOperator after completing the two-part expression
        // This allows proper parsing of operators like 'or' that follow s/tr/y expressions
        self.set_lexer_context(crate::lexer::LexerContext::ExpectingOperator);

        // Force a fresh token fetch to ensure the context change takes effect
        // Skip any trivia and refresh the current token with the new context
        self.skip_trivia();
    }

    /// Get the matching closing delimiter for an opening delimiter
    fn get_closing_delimiter(opening: char) -> char {
        match opening {
            '(' => ')',
            '[' => ']',
            '{' => '}',
            '<' => '>',
            // For symmetric delimiters, the closing is the same as opening
            ch => ch,
        }
    }

    /// Check if current token is a DELIMITER with specific char
    fn at_delimiter(&self, delimiter: char) -> bool {
        self.current_delimiter().is_some_and(|d| d == delimiter)
    }

    fn current_delimiter(&self) -> Option<char> {
        // Do NOT skip trivia here; callers should handle trivia explicitly.
        if let Some((SyntaxKind::DELIMITER, text)) = self.lexer.peek_token() {
            let mut chars = text.chars();
            if let (Some(delimiter), None) = (chars.next(), chars.next()) {
                return Some(delimiter);
            }
        }
        None
    }

    /// Expect a DELIMITER token with specific text
    fn expect_delimiter(&mut self, delimiter: char) {
        // Ensure any trivia before the delimiter is consumed
        self.skip_trivia();
        if self.at_delimiter(delimiter) {
            // Consume the actual delimiter token
            self.bump();
        } else {
            let msg = format!(
                "Expected delimiter '{}', found {:?}",
                delimiter,
                self.current_kind()
            );
            self.error(&msg);
        }
    }
}
